### ISSUE TITLE
Leaked token

### ISSUE THREAD

**Issue by jasonhaxstuff** [Kenny-McCool/AviBotDev#1]
In your music-related code, you instantiate the YouTube object (named `searcher`) with a token put right into the file. Your bot token is also clearly visible in the `config.json` and `auth.json` files.

Tokens are meant to be treated like passwords. Bots come around all the time scraping tokens from unsuspecting developers' repositories, getting them banned from using the service by spamming the API.

I would recommend putting `config.json` and `auth.json` down in a `.gitignore` file (learn more [here](https://help.github.com/en/github/using-git/ignoring-files)) and creating `config.example.json` and `auth.example.json` files with dummy data in them to ensure that people understand where to put their tokens and such.

**Comment by Kenny-McCool** [comment]
I appreciate the concern, but the tokens shown in the config here are old ones from ages ago, no longer active. I was going to replace it with "your token here", but never got around to it because this is more of a, "do stuff now polish it for release later" repository.
